### ISSUE TITLE
bmtFiles check empty dir can be made a little more efficient

### ISSUE THREAD

**Issue by harleypig** [gavinlyonsrepo/bashmultitool#1]
You can improve the efficiency of the bmtFiles check empty dir function by changing lines 20-26 to the following:

    [[ -n "$(find "$2" -maxdepth 0 -empty -print)" ]] && return 0 # is empty
    return 2 # is not empty

**Comment by gavinlyonsrepo** [comment]
Thanks for feedback, 
I understand what you are saying but this code snippet wont work as that function also returns 3 for another circumstance. 
I will look into it more.
