### ISSUE TITLE
hey quick question/ possible error

### ISSUE THREAD

**Issue by rayiik** [gavinlyonsrepo/bashmultitool#2]
hey in misc functions
```bash
	if [ -n __BMT_START_WATCH ] 
		then
			local stopWatchVar=0
			stopWatchVar=$(bmtMiscFunc now)
			bmtMiscFunc elapsed "$__BMT_START_WATCH" "$stopWatchVar" 
			return 0
		else
			return 2
		fi
	;;
``` 

under stopwatch #6 shouldnt it be
```bash
if [[ -n "$__BMTSTART_WATCH" ]];
     then
```
i could be wrong I'm fairly new to programming.

**Comment by gavinlyonsrepo** [comment]
HI 

Yes that's correct. that's a typo, I should have spotted that as shellcheck flags it as an  issue(SC2154) and I always run shellcheck on scripts before i use/publish them.
The stopwatch function still works  , that "if statement" is only there to catch a user error: if they run "stopWatch" before they run "startWatch". and return error code 2. 

thanks

**Comment by rayiik** [comment]
hey no worries i just wasn't sure if there was some convention i didn't know about, i only noticed it because I'm building a bash snippet manager / command line IDE  and that and i happened to be doing it in vs code and it point it out to me. I've only been programming 6 months and exclusively in bash so far and its got some jacked up exceptions (like I've seen code that's set up to intentionally fail which still doesn't make sense to me).
